### ISSUE TITLE
MSOffice2011Update cannot download update dmg since 14.7.4

### ISSUE THREAD

**Issue by hymmm** [autopkg/recipes#204] opened 2017-05-17 03:12 UTC
Since this May, Office2011 update (14.7.4) seems that is not able to be detected via
https://www.microsoft.com/mac/autoupdate/0409MSOf14.xml as until now.

Newest office autoupdater can download it, so another spec xml is provided from MS.
(but I don't know where it is).

**Comment by timsutton** [comment] 2017-05-17 06:24
Perhaps the 2011 updates feed has moved to the newer system used by that of he 2016 recipes.

**Comment by gregneagle** [comment] 2017-05-18 18:36
I can confirm the latest update is not in the https://www.microsoft.com/mac/autoupdate/0409MSOf14.xml feed.
Right now I'm just manually downloading the update and providing it to the .munki recipe using the `--pkg` option.
Microsoft AutoUpdate refuses to even _run_ on my test machine with Office2011, so reverse engineering this is not likely to happen by me any time soon.

**Comment by gregneagle** [comment] 2017-05-18 18:37
If anyone has a direct download link to the latest Microsoft AutoUpdate update that would be helpful as searching microsoft.com has proved frustrating.

**Comment by timsutton** [comment] 2017-05-18 18:37
This should be resolved in https://github.com/autopkg/recipes/commit/1d4fc94191bbe85d60c4a271ceb16d992ac6fea6. If anyone can confirm (besides me) we can close this issue.

**Comment by timsutton** [comment] 2017-05-18 18:39
A couple of days ago, @pbowden-msft confirmed in the #microsoft-office Macadmins Slack channel that the Office 2011 updates had moved to the newer CDN that the Office 2016 updates has been using for a while.

**Comment by gregneagle** [comment] 2017-05-18 18:40
Works for me!

**Closed** 2017-05-18 18:41 UTC
