### ISSUE TITLE
OracleJava8 u 65 not last update ?

### ISSUE THREAD

**Issue by Thomgi** [autopkg/recipes#124] opened 2015-11-25 17:56 UTC
Hi there,

It doesn't seems that the real last version of JRE 8 is take by autopkg/autopkgr.

As seen on the webpage use by autopkg : http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

There is a JRE 8u66 out while autopkg download JRE 8u65.

Is it an issue from autopkg, or "work as intended" ? :)
Thank as usual for your great job and answer.

**Comment by gregneagle** [comment] 2015-11-25 18:18
Works as intended. The recipe gets "CPU" updates and ignores "PSU" updates.

Oracle quote: "Java PSU releases should only be used if you are being impacted by one of the additional bugs fixed in that version."

```
% autopkg info OracleJava8.download
Description:         Download recipe for Oracle's Java 8. Finds and downloads the latest Oracle Java 8 JRE CPU release.
                     
                     Read more about CPU and PSU releases here:
                         http://www.oracle.com/technetwork/java/javase/downloads/cpu-psu-explained-2331472.html
                     
                     To use this recipe, you must accept the Oracle Binary Code License Agreement for Java SE.
                     http://www.oracle.com/technetwork/java/javase/terms/license/index.html
                     
Identifier:          com.github.autopkg.download.OracleJava8
Munki import recipe: False
Has check phase:     True
Builds package:      False
Recipe file path:    /Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/OracleJava/OracleJava8.download.recipe
Input values: 
 
    NAME = OracleJava8;
```

**Closed by gregneagle** 2015-11-25 18:18 UTC

**Comment by gregneagle** [comment] 2015-11-25 18:26
See also https://groups.google.com/d/topic/autopkg-discuss/7GOxCocZPak/discussion
