### ISSUE TITLE
Spotify 1.0.84.344.gfc674f6f Crashes at Launch

### ISSUE THREAD

**Issue by KSchmeeds** [autopkg/recipes#256] opened 2018-07-11 15:30 UTC
The latest version of Spotify 1.0.84.344.gfc674f6f will crash at launch.

Process:               Spotify [7594]
Path:                  /Applications/Spotify.app/Contents/MacOS/Spotify
Identifier:            com.spotify.client
Version:               1.0.84.344.gfc674f6f (1.0.84.344.gfc674f6f-17)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Spotify [7594]
User ID:               1951396235

Date/Time:             2018-07-11 10:29:39.690 -0500
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        E415ACF6-9C6D-11F9-A62B-7C3EAAD2AB66

Time Awake Since Boot: 4400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Applications/Spotify.app/Contents/MacOS/Spotify
  Reason: no suitable image found.  Did find:
	/Applications/Spotify.app/Contents/MacOS/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework: stat() failed with errno=13

Binary Images:
       0x10052b000 -        0x101f7ffff +com.spotify.client (1.0.84.344.gfc674f6f - 1.0.84.344.gfc674f6f-17) <E1D1976D-5ECD-3242-BFE6-8DD54166DAA4> /Applications/Spotify.app/Contents/MacOS/Spotify
       0x10a84e000 -        0x10a898acf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld
    0x7fff2d62e000 -     0x7fff2d8bcff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <E0B8B5D8-80A0-308B-ABD6-F8612102B5D8> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2e6f6000 -     0x7fff2e789ff7  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <EB35D3EC-56EA-33E6-98DC-BDC3A5FA8ACE> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff2ec55000 -     0x7fff2f0f6fef  com.apple.CoreFoundation (6.9 - 1454.90) <E5D594BF-9142-3325-A62D-CF4AAF472642> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2f0f8000 -     0x7fff2f708fef  com.apple.CoreGraphics (2.0 - 1161.21) <375C477F-5A89-3C49-9B63-373C81A63F7E> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff563a8000 -     0x7fff563c4ffb  libresolv.9.dylib (65) <E8F3415B-4472-3202-8901-41FD87981DB2> /usr/lib/libresolv.9.dylib

Model: MacBookPro11,5, BootROM MBP114.0184.B00, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: Magic Keyboard
USB Device: Yubikey 4 OTP+U2F+CCID
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by izcet** [comment] 2018-09-06 14:41
I had the same issue. I found the source and a fix for the problem, but not the cause or solution.

If you check the errno provided by `stat()` (`strerror(13)`) it shows the error as `Permission denied`. Check the permissions on all the directories in the path `/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework.framework`

For example,
```
$ ls -la "/Applications/Spotify.app/Contents/Frameworks"
total 0
drwxr-xr-x  4 root  admin  128 Aug 20 11:14 .
drwxr-xr-x  8 root  admin  256 Aug 20 11:16 ..
drwxr--r--  5 root  admin  160 Aug 20 11:16 Chromium Embedded Framework.framework
drwxr-xr-x  3 root  admin   96 Aug 20 11:14 Spotify Helper.app
```
This won't work for us because only root can enter the directory `Chromium Embedded Framework.framework`, but we need to from any user (since we aren't running Spotify as root... I hope)


I solved mine with (run as root or with `sudo`) 
```
chmod +x /Applications/Spotify.app/Contents/Frameworks/Chromium Embedded Framework.framework
```

You should see the following:
```
$ ls -la "/Applications/Spotify.app/Contents/Frameworks"
total 0
drwxr-xr-x  4 root  admin  128 Aug 20 11:14 .
drwxr-xr-x  8 root  admin  256 Aug 20 11:16 ..
drwxr-xr-x  5 root  admin  160 Aug 20 11:16 Chromium Embedded Framework.framework
drwxr-xr-x  3 root  admin   96 Aug 20 11:14 Spotify Helper.app
```

Check for yourself that it's the same directory causing problems. Your results may vary.

**Comment by gregneagle** [comment] 2018-09-06 16:29
Does the Munki postlfight script here: https://github.com/autopkg/recipes/blob/master/Spotify/Spotify.munki.recipe#L36-L41 not address this _Spotify_ issue? I'me pretty sure it does. Other recipes that use the Spotify.download recipe as a base and then, say, create a package would have to implement their own fixes. I don't see an issue with the two Spotify recipes in this repo.

**Comment by gregneagle** [comment] 2018-09-07 17:17
Going to close this since I think it was addressed in July. Please reopen with details if you determine it is not actually addressed.

**Closed by gregneagle** 2018-09-07 17:17 UTC

**Comment by izcet** [comment] 2018-09-07 18:02
Hi @gregneagle, sorry I'm really new to this and haven't done too much investigation myself. I just had this exact issue happen to me two days ago when updating to the latest version of Spotify (released a day prior), and found this thread with the same problem. If this was addressed in July I wonder if it's the same issue or something else with the same symptoms. 

Please let me know if this is the right place to discuss this or if I should bring this topic up somewhere else.

**Comment by gregneagle** [comment] 2018-09-07 18:20
Which recipe are you running?  If you'd like others to look into this and help you need to provide more details. We need to know, step by step, how you get to a state where Spotify doesn't launch.

I use the current Spotify.munki recipe to get the current Spotify into my Munki repo. Munki then installs it on my Mac. I can launch Spotify.
